// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izigohixbhppyyoueutp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6aWdvaGl4YmhwcHl5b3VldXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjA3MTEsImV4cCI6MjA2NTUzNjcxMX0.QbxMI8fxqiQlxcWwJF1q-7DSHrIdOmOG3qCP-ckd9fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);